Dev
SphericalPotatoInVacuum/3D_Renderer pull request #1
Opened 2021-05-11 16:52 UTC by SphericalPotatoInVacuum

2021-05-25 13:38 UTC, DimaTrushin requested changes
Я пробежался по тексту. И несколько офигел от количества всего. Это первое приближение. После правок я смогу посмотреть и оценить следующий уровень ошибок.

Еще жутко неудобно сделал, что разделил h и cpp файлы по разным папкам, приходится прыгать козленкам по папкам, чтобы изучить один и тот же кусок кода. Релевантные вещи должны быть вместе.

2021-05-25 13:38 UTC, DimaTrushin commented on src/main.cpp
> +const size_t WIDTH = 1000;
глобальные константы.
Во-первых, constexpr.
Во-вторых, не надо делать глобальные константы. Ты можешь сделать локальные переменные в нужной функции.
В-третьих, не используй чистый капс для переменных. Капс с подчеркиваниями используется только для макросов. Иначе их хер отличишь от переменных.

2021-05-25 13:38 UTC, DimaTrushin commented on src/main.cpp
> +int main() {
Эта функция -- помойка. Никогда не пиши функции длиной в миллион строк. Их не возможно читать и поддерживать. Общие рекомендации по организации такого кода следующие:
1) Создать объект Application, который обеспечивает контекст для всей твоей программы.
2) Все ресурсы приложения являются переменными внутри Application. 
3) Application имеет метод run или exec для запуска обработчика сообщений от пользователя.
4) В конструкторе Application инициализирует в правильном порядке все свои ресурсы.
5) В конструкторе Application так же подписывается на все входящие сообщения из экосистемы операционной среды.
6) В обработчике событий у Application находится логика на какие сообщения пользователя он отвечает и как.

2021-05-25 13:38 UTC, DimaTrushin commented on src/main.cpp
> +  std::vector<yar::Triangle> triangles = {
Если надо создавать сложные объекты, а конструирование занимает много места, надо выделить конструирование в отедельную функию. Заодно ее имя скажет, что ты именно конструируешь. например тут можно сделать так
```cpp

auto triangles = getPenisCarcas();
std::vector<yar::Triangle> getPenisCarcas() {
return { {{{1, 1, -1, 1}, {0, -1, 0, 1}, {-1, 1, -1, 1}}, yar::Color{255, 0, 0}},
             {{{1, 1, 1, 1}, {0, -1, 0, 1}, {1, 1, -1, 1}}, yar::Color{0, 255, 0}}, 
             {{{-1, 1, 1, 1}, {0, -1, 0, 1}, {1, 1, 1, 1}}, yar::Color{0, 0, 255}},
             {{{-1, 1, -1, 1}, {0, -1, 0, 1}, {-1, 1, 1, 1}},  yar::Color{255, 255, 0}}};
}

```

2021-05-25 13:38 UTC, DimaTrushin commented on src/main.cpp
> +  while (window.isOpen()) {
Вот этот код надо выделить в метод run или exec (или любое другое аналогичное название) у Application.

2021-05-25 13:38 UTC, DimaTrushin commented on src/main.cpp
> +    while (window.pollEvent(event)) {
Я так и не понял, какого хрена в sfml нужно два вложенных цикла для простой обработки событий.

2021-05-25 13:38 UTC, DimaTrushin commented on src/main.cpp
> +          if (sf::Keyboard::isKeyPressed(sf::Keyboard::A)) {
В обработчике событий никогда не пиши явно код для обработки, вместо этого вызывай соответствующую функцию. Например тут надо
handleKeyPressing(...);
Иначе просто не возможно будет уследить за всеми событиями, что ты тут обрабатываешь. Это нарушение уровня абстракции. Тут важнее увидеть, что за список обрабатываемых событий и что за действия ты для них вызываешь. За список отвечает switch с константами в case-ах, а за действия -- имена функций. Что именно функции делают -- деталь имплементации.

2021-05-25 13:38 UTC, DimaTrushin commented on src/main.cpp
> +    float current_time = clock.getElapsedTime().asSeconds();
Какого хрена время измеряется для всего внутреннего цикла? Это так и задумано?

2021-05-25 13:38 UTC, DimaTrushin commented on src/main.cpp
> +    last_time = current_time;
Вообще не лучшая стратегия измерения времени. Самое лучшее решение описано тут
https://stackoverflow.com/questions/879408/c-function-wrapper-that-behaves-just-like-the-function-itself
Надо смотреть на ответ Мыколы Голубева + комментарии к нему. Этот подход был в свое время описан Страуструпом и продвигался Александреску в его докладе Generic Locking (можно загуглить на ютюбе).

2021-05-25 13:38 UTC, DimaTrushin commented on src/main.cpp
> +    for (int i = 0; i < WIDTH * HEIGHT; ++i) {
Это что за дичь? Это явно должно быть зашито в метод.Судя по всему ты пытаешься заполнить попиксельно экран. Какого хрена? Почему нет отдельного метода, который возвращает экран целиком? RVO тебя спасет при подобной манипуляции.

2021-05-25 13:38 UTC, DimaTrushin commented on src/main.cpp
> +
В коде ниже очень сложно выделить роль каждого сегмента. Не понятно, что именно делается и зачем. Я бы ожидал тут вызов одной или двух функций в худшем случае.

2021-05-25 13:38 UTC, DimaTrushin commented on src/Kernel.hpp
> +class Kernel {
Что за дичь? Я правильно понимаю, что класс нигде не используется?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/World.hpp
> + private:
Приватные данные в конец класса.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/World.hpp
> +  std::vector<Object *> m_objects;
Судя по всему World не хранит объекты, а хранит указатели на них. Кто тогда владеет объектами?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/World.hpp
> +  const std::vector<Object *> get_objects() const;
Я правильно понимаю, что сейчас имплементация World -- это просто контейнер указателей?
Судя по этому методу, ты вместо того, чтобы предоставить интерфейс контейнера пробросил контейнер наружу. Кроме того, офигенно, что ты возвращаешь вектор в виде копии! Я объясню, что тут происходит
1) Ты делаешь лишнюю копию, когда делаешь return из функции
2) Ты делаешь лишнюю копию, когда присваиваешь результат к какой-то переменной, потому что из константного вектора нельзя взять данные, их можно только скопировать. В результате, у тебя тут 2 лишнии копии, потому что надо было написать 
```cpp
const std::vector<Object *>& get_objects() const;
```
Но вообще в целом объект World получается не нужным.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Triangle.hpp
> +  std::array<glm::vec4, 3> m_points;
Первый вопрос: почему std::array, а не Eigen::Matrix статичного размера?
Второй вопрос: за что отвечают эти все точки. m_points еще понятно (не понятно почему они 4-мерные). Кто такие m_vecs? Кто такие m_lines?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Triangle.hpp
> +  std::array<glm::vec2, 3> m_lines;  // Ax + B = y -- A and B for all m_vecs
А что это за комментарий? Я так и не понял, что он описывает ибо в обозначениях выше нет ни A ни B. Толку от комментария не сильно много.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Triangle.hpp
> +float edge_function(glm::vec2 vec, glm::vec2 point);
Что это за функция? Что она делает? Где глагол в названии функции?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +yar::Triangle::Triangle(std::array<glm::vec4, 3> points, Color color)
Функции в cpp файле должны идти в том же порядке, что и в хедере.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +yar::Triangle::Triangle(std::array<glm::vec4, 3> points)
Агрументы с большой локальной частью должны передаваться по ссылке. Ибо иначе ты делаешь два копирования:
1) в локальную переменную
2) в переменные класса
std::array весь хранится локально.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +  if (list.size() != 3) {
Я бы сказал, что это не exception, а assert. Ибо это косяк программиста, а не исполнения среды.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +  std::array<glm::vec4, 3> points;
- Зачем столько лишних копирований данных туда сюда? Вообще, почему ты не написал
```cpp
yar::Triangle::Triangle(std::initializer_list<glm::vec4> list, yar::Color color) 
  : m_points(list), m_color(color) {}
```
?
- Кроме того, другой вопрос. А где определение других компонентов? У тебя еще какие-то там есть m_vec и m_lines. Где они определяются?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +  *this = yar::Triangle(points, color);
А это уже полный пиздец. Почему НЕ делигируешь? И нахрена один и тот же массив копировать 4 раза?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +yar::Triangle::Triangle(std::array<glm::vec4, 3> points, Color color)
Вместо того, чтобы писать каждую функцию писать с явным квалификатором namespace-а, напиши
```cpp
namespace yar {
Triangle::Triangle(...) {...}
...
}
```

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +float edge_function(glm::vec2 vec, glm::vec2 point) {
Почему эта функция в глобальном namespace?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +    point /= point.w;
Что есть w = 0?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +void yar::Triangle::normalize() {
Это явно не normalize должно называться. Просто от такого метода для вектора я бы ожидал деления на длину. Нужно более удачное имя.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +yar::Triangle yar::Triangle::operator*(const glm::mat4 &mat) const {
Обычно операторы пишутся так:
1) Сначала пишется in place версия
2) Потом пишется не in place версия, в которой вызывается in place решение.

И ты правда треугольник на матрицу справа умножаешь? При этом матрица как развернута? У тебя все транспонировано стандартным вещам из линала?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +    triangle.m_points[i] = mat * m_points[i];
Почему не напишешь просто
```cpp
for (auto& point : triangle.m_points) 
  point = mat * point;
```
? Плюс как я вижу у тебя оператор умножения все таки слева на матрицу внутри зашит. А снаружи у тебя будет работать в другую сторону.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +    if (edge_function(m_vecs[i], p) > 0) {
Поди догадайся, что это за условие.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +bool yar::Triangle::is_inside(glm::vec2 point) const {
Мне не очень понятен смысл этой функции. У тебя проверяется про 2D точку лежит ли она внутри 3D треугольника. Тут вроде как проекции нехватает, чтобы это определить.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Triangle.cpp
> +std::array<glm::vec4, 3> yar::Triangle::get_points() const {
почему by value, а не by const reference?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Triangle.hpp
> +    float w0 = edge_function(m_vecs[1], point - glm::vec2(m_points[2])) / den;
что если den = 0?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Screen.cpp
> +    : m_picture(width, height),
Инициализируй ресурсы в списке инициализации в ТОМ ЖЕ порядке, в каком данные объявлены в теле класса. Потому что инициализироваться они будут именно в том порядке, в котором объявлены, а не в том, который указан тут.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Screen.cpp
> +      m_zbuf(width * height, -1) {}
Все ли данные допустимы? Надо ли ставить assert-ы на недопустимые значения входных параметров?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Screen.cpp
> +      m_zbuf(width * height, -1) {}
Что за магическая константа "-1"?
Сделай
static constexpr const float kMinimalZValue = -1.;
Или что-то в таком же духе. Аналогично для максимального значения. Просто иначе у тебя какие-то странные константы, которые не понятно что значат. И если будет рассинхрон в формулах, то ты замучаешься эти константы поправлять.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Screen.cpp
> +  m_zbuf.assign(m_width * m_height, 1);
Магическая константа "1".

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Screen.cpp
> +  if (z < m_zbuf[x * m_width + y]) {
где assert проверяющий, что x и y в зоне допустимых размеров?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Renderer.hpp
> + private:
У тебя непостоянство с порядком данных для классов. Где-то публичные данные в начале, где-то наоборот. Приведи к единому стандарту.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Renderer.hpp
> +  size_t m_width;
Выглядит как дублирование данных. Это размеры m_screen? Если да, то зачем они тут дублируют. А если нет, то надо более адекватное название дать, чтобы было понятно что это.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Renderer.cpp
> +float frand() {
Судя по всему у тебя есть математические хелперы в виде функций. Их надо все вывести в отдельный файл с отдельным namespace и звать оттуда.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Renderer.hpp
> +  yar::World& m_world;
Никогда не храни ссылку на объект. Ты не сможешь ее никогда поменять. Если нужно ссылаться на кого-то, то уж лучше передавай указатель.

У тебя есть два варианта дизайна:
1) Renderer не инициализируется камерой, миром и экраном. Вместо этого в конструкторе он инициализирует только то, что ему надо для работы (все свои внутренние буферы). А камера, экран и мир ему передаются в методе render. При вызове проверяется корректность согласованности данных (размер экрана правильный и т.д.).
2) Renderer хранит камеру, мир и экран внутри себя и при создании согласует их размеры и другие данные.

Я не вижу необходимости в конструкторе привязываться к конкретной камере и миру, а экран хранить внутри. У тебя получилось половинчатое решение.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Renderer.cpp
> +    for (yar::Triangle triangle : object_ptr->get_triangles()) {
Вложенные циклы -- бан. Это означает нарушение уровня абстрации. Кроме того, это проблематично в плане контроля корректности. Тело цикла может обратиться клюбым данным вне него. Лучше в цикле вызывать одну функцию и через ее параметры явно указывать, что ты туда передаешь. Это во-первых, избавит тебя от большого количества ошибок по нарушению инвариантов цикла, а во-вторых, имя функции скажет, что именно за работу ты тут выполняешь.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Renderer.cpp
> +  glm::mat4 mvp;
что за Most Valuable Person?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Renderer.cpp
> +  glm::mat4 view = glm::inverse(m_camera.get_transform_matrix());
Строчки 21-23 выглядят как построение чего-то вспомогательного. Выглядит так, что view и projection тебе отдельно не нужны, а нужно их произведение. И только оно используется потом внизу для построения mvp.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Renderer.cpp
> +    mvp = projection * view * model;
раз ты тут впервые используешь переменную, тут ее и объявляй. Мы не на сях пишем, где надо писать полотно из переменных в начале функции. Компилятор разберется, как правильно выделить память. Учитывая, что под model ты выделяешь память внутри цикла.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Renderer.cpp
> +    float xf = static_cast<float>(x) / m_width * 2 - 1;
Наличие явного статик каста -- ошибка проектирования. Что у тебя тут делается? Судя по всему ты пересчитываешь одни координаты в другие. Тогда за это должна отвечать функции с говорящим названием и касты скрыты внутри.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Renderer.cpp
> +      float yf = static_cast<float>(y) / m_height * 2 - 1;
Что делает тело этого цикла?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Renderer.cpp
> +      if (std::abs(point.x) <= 1 && std::abs(point.y) <= 1 &&
Вместо сложного условия под if-ом, надо написать функцию с говорящим названием, которая делает эту проверку. Например is_something_true и вызывать ее тут. Это повисит читаемость кода.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Renderer.cpp
> +          triangle.interpolate(yar::Color{255, 0, 0}, yar::Color{0, 255, 0},
Опять магические константы. Почему цвета именно так заданы? Кроме того, почему для чистых цветов не сделано констант вида Color::Red, Color::Green, Color::Blue. Делаешь публичные static constexpr константы типа Color внтри класса Color.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Picture.hpp
> +  Color operator*(const T& p) const {
Во-первых, почему шаблонный тип? На какие типы ты предполагаешь умножение? Если только на целые, то можно сделать uint8_t и возложить обязанность конвертации на преобразование типов при ADL.
Во-вторых, если уж писать операторы то надо так
```cpp
Color& operator*=(uint8_t multiplier) {
  r *= multiplier;
  g *= multiplier;
  b *= multiplier;
  return *this;
}

friend Color operator*(const Color& color, uint8_t multiplier) {
  Color result = color;
  result *= multiplier;
  return result;
}
friend Color operator*(uint8_t multiplier, const Color& color) {
  return color * multiplier;
```
Наличие uint8_t в качестве аргумента позволит тебе использовать любой тип который конвертируется и не будет плодить лишних шаблонов. От шаблона тут пользы никакой. Ты вместо конвертации на месте будешь для каждой конвертации сначала генерить код оператора, а потом все равно внутри своего оператора у тебя будет конвертация во время выполнения операции умножения.
В-третьих, лучше добавить using BaseType = uint8_t; и пользоваться этим алиасом везде вместо чистого типа. Это позволит локализовать все решения.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Picture.hpp
> +  Color operator*(const T& p) const {
Судя по всему T  у тебя маленький тип. Маленькие типы всегда передавай by value. А если ты уж хочешь писать шаблонный код, то надо делать perfect_forwarding. Делается так
```cpp
template<class T>
void f(T&& arg) {...}
template<class T>
void g(T&& arg) {
  f(std::forward<T>(arg);
}
```
Для базовых типов это все равно глупость и лучше by value.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Picture.hpp
> +  std::shared_ptr<Color> m_data_ptr;
Это что еще за фигня?
Во-первых, shared_ptr на НЕ константный объект. Привет баги. Ты умрешь отлаживать такое.
Во-вторых, вся суть оптимизации графики заключается в том, чтобы все данные лежали рядом. А у тебя указатель да еще и shared. Не удивлюсь, если ты там еще и данные под массив выделяешь через new (надеюсь это не так...)

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Picture.cpp
> +      m_data_ptr((yar::Color*)malloc(width * height * sizeof(yar::Color)),
Это пиздец.  У меня нет слов. Я угадал. Я даже не знаю, что сказать...
Что мешало сделать std::vector<Color>?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Picture.cpp
> +      m_data_ptr((yar::Color*)malloc(width * height * sizeof(yar::Color)),
Если ты тут выделяешь ресурс, то надо его в деструкторе хотя бы чистить. Потому что shared_ptr будет хранить только указатель на выделенную память, а не саму память. И при уничтожении объекта, ты тут течешь похлеще твоей подружки.

Вообще, чтобы не косячить, в плюсах есть правило: не пользоваться new и delete, функций malloc НЕ существует, а если надо выделить std::unique_ptr или std::shared_ptr, то надо пользоваться std::make_unique и std::make_shared.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Picture.cpp
> +    m_data_ptr.get()[i] = {0, 0, 0};
Плюс вектора в том, что ты можешь инициализировать его дефолтно при создании.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Picture.cpp
> +const yar::Color* yar::Picture::get_pixels() const {
Не уверен, что хорошая идея иметь этот метод в классе. Ибо у тебя нарушение инкапсюляции. Ты по сути просто сообщаешь детали реализации. Где тебе это надо? Лушче уж сделать у Picture совместимость с stl итераторами и for циклом, через создание метода begin() и end() по всем парам пикселей. Я просто не верю, что тебе это где-то понадобится, если у тебя есть оператор доступа к пикселям.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Picture.cpp
> +yar::Color& yar::Picture::operator()(size_t x, size_t y) {
У такого оператора хорошо бы сделать константную версию, чтобы можно было к константным объектам применять.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Object.hpp
> +         const std::vector<yar::Triangle>& triangles);
Обычно, когда ты объект конструируешь, то ты строишь его из временных данных. которые хочешь поглатить. Потому аргументы конструктора очень редко бывают константными ссылками. Точнее, есть два подхода
```cpp
class A {
  A(const B& b) : b_(b) {}
  A(B&& b)  : b_(std::move(b)) {}
 B b_;
};
```
и второй подход
```cpp
class A {
  A(B b) : b_(std::move(b)) {}
 B b_;
};
```
При дешевом муве разницы между этими подходами нет. Но при дорогом муве первый предпочтительнее.

У вектора дешовый мув, потому его можно смело принимать by value и перемещать внутрь в списке инициализации.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Object.hpp
> +  Object(glm::vec3 pos, glm::vec3 rot,
У тебя какая-то маниакальная любовь к большому количеству конструкторов. Готов поспорить, что половины из них не используешь.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Picture.hpp
> +  Picture(){};
Уф, как плохо. Лучше уж 
```cpp
Picture() = default;
```
А вообще не понятно зачем тебе дефолтный конструктор, если у тебя объект не позволяет себя после создания менять. Это создает бесполезную картинку. Я бы вообще не делал дефолтного конструктора.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Entity.hpp
> +  Entity(){};
Entity() = default;

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/include/YAR/Entity.hpp
> +  glm::mat4 get_transform_matrix() const;
почему by value?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Entity.cpp
> +  update_matrices();
А почему matrices? там же одна матрица? Или я чего-то не заметил?

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Entity.cpp
> +  update_matrices();
Вообще говоря можно создать статическую функцию по соозданию матрицы вида
```cpp
glm::mat4 makeTransformMatrix() {
  glm::mat4 result;
  ....
  return result;
}
```
И тогда можно написать
```cpp
Entity::Entity(glm::vec3 pos, glm::vec3 rot)  
  : m_position(pos),
    m_rotation(rot),
    m_transform_matrix(makeTransformMatrix()) {}
```
RVO поможет избежать лишних проблем.

2021-05-25 13:38 UTC, DimaTrushin commented on libs/YAR/src/Entity.cpp
> +  glm::mat4 rotation = glm::mat4(1.0f);
Я не осилил.

2021-06-01 22:21 UTC, SphericalPotatoInVacuum commented on libs/YAR/src/Triangle.cpp
> +  std::array<glm::vec4, 3> points;
Там всё сводится к одному конструктору, который в конце вызывает update(), которая в свою очередь обновляет m_vec

2021-06-01 22:34 UTC, SphericalPotatoInVacuum commented on libs/YAR/src/Triangle.cpp
> +    point /= point.w;
Получается при нулевом расстоянии точки до камеры, что невозможно из-за добавленного клиппинга

2021-06-01 22:35 UTC, SphericalPotatoInVacuum commented on libs/YAR/src/Triangle.cpp
> +void yar::Triangle::normalize() {
Переименовал в project_to_3d потому что получается проекция на трёхмерное пространство, лучше не придумал ничего

2021-06-01 22:45 UTC, SphericalPotatoInVacuum commented on libs/YAR/src/Triangle.cpp
> +bool yar::Triangle::is_inside(glm::vec2 point) const {
Я использую эту функцию уже после того как спроецировал треугольник на 2D плоскость экрана, проекция есть, просто снаружи производится

2021-06-02 01:57 UTC, SphericalPotatoInVacuum commented on libs/YAR/include/YAR/Triangle.hpp
> +  std::array<glm::vec4, 3> m_points;
4-мерные потому что работаем в однородных координатах для лёгкого перехода между системами координат. m_vecs это векторы, соответствующие рёбрам, а m_lines не нужны, их выпилил

2021-06-02 01:59 UTC, SphericalPotatoInVacuum commented on libs/YAR/include/YAR/Triangle.hpp
> +float edge_function(glm::vec2 vec, glm::vec2 point);
Переименовал в get_signed_cross_product_length, если честно не знаю как сократить, чтобы сохранился смысл

2021-06-02 02:02 UTC, SphericalPotatoInVacuum commented on libs/YAR/include/YAR/Triangle.hpp
> +    float w0 = edge_function(m_vecs[1], point - glm::vec2(m_points[2])) / den;
То площадь треугольника 0 и нам вообще по хорошему нет резона его отображать, пользователь плохой человек если такой треугольник далл, докинул ассерт потому что считаю, что имею право вылететь если дали дичь вместо данных

2021-06-03 11:48 UTC, DimaTrushin approved these changes
Заливай как есть. Стало сильно лучше. Есть еще небольшие дефекты. Но уже сейчас прям хорошо.

2021-06-03 11:58 UTC, merged